#! /usr/bin/env python
# encoding: utf-8

top = '.'
out = 'build'

def options(opt):
    opt.load('python')
    opt.load('compiler_c')

def configure(conf):
    conf.load('compiler_c')
    conf.load('python')
    conf.check_python_version((3,4))
    conf.check_python_headers()
    conf.env.append_value('FRAMEWORK_COCOA', 'Cocoa')

def build(bld):
    import objp.o2p
    import objp.p2o
    import main
    objp.o2p.generate_objc_code(main.PyMain, 'autogen')
    objp.p2o.generate_python_proxy_code('MyCallback.h', 'autogen/MyCallbackProxy.m')
    bld(
        features = 'c cshlib pyext',
        source   = 'autogen/MyCallbackProxy.m',
        target   = 'MyCallbackProxy')
    
    bld.program(
        features      = 'c cprogram pyembed',
        target        = 'callback',
        source        = 'main.m autogen/PyMain.m autogen/ObjP.m MyCallback.m',
        use           = 'COCOA',
        includes      = '. autogen',
    )
    bld(
        rule = 'cp ${SRC} ${TGT}',
        source = bld.path.make_node('main.py'),
        target = bld.path.get_bld().make_node('main.py'),
    )

from waflib import TaskGen
@TaskGen.extension('.m')
def m_hook(self, node):
    """Alias .m files to be compiled the same as .c files, gcc will do the right thing."""
    return self.create_compiled_task('c', node)

