#! /usr/bin/env python
# encoding: utf-8
# Chris Pickel, 2011

VERSION='0.0.1'
APPNAME='hello_world'

top = '.'
out = 'build'

def options(opt):
    opt.load('python')
    opt.load('compiler_c')

def configure(conf):
    conf.load('compiler_c')
    conf.load('python')
    conf.check_python_version((3,2))
    conf.check_python_headers()
    conf.env.append_value('FRAMEWORK_COCOA', 'Cocoa')
    conf.env.ARCH = ['i386', 'x86_64']

def build(bld):
    import objp.p2o
    objp.p2o.generate_python_proxy_code(['Foo.h', 'Bar.h'], 'autogen/proxies.m')
    bld(
        features = 'c cshlib pyext',
        source   = 'autogen/proxies.m Foo.m Bar.m',
        target   = 'proxies',
        use      = 'COCOA',
    )
    bld(
        rule = 'cp ${SRC} ${TGT}',
        source = bld.path.make_node('main.py'),
        target = bld.path.get_bld().make_node('main.py'),
    )

from waflib import TaskGen
@TaskGen.extension('.m')
def m_hook(self, node):
    """Alias .m files to be compiled the same as .c files, gcc will do the right thing."""
    return self.create_compiled_task('c', node)

@TaskGen.feature('cshlib')
@TaskGen.after('apply_obj_vars', 'apply_link')
def kill_flag(self):
    fl = self.link_task.env.LINKFLAGS
    if '-bundle' in fl and '-dynamiclib' in fl:
         fl.remove('-bundle')
         self.link_task.env.LINKFLAGS = fl

# -*- indent-tabs-mode: t -*-
